### ISSUE TITLE
Corrupt war file

### ISSUE THREAD

**Issue by Markus1954** [l0y/learnjava5e-web#1]
I just opened the war file in Notepad++ and there was a lot of gobbledy gook.

`PK  "otO            	  META-INF/þÊ   PK           PK  "otO               META-INF/MANIFEST.MFóMÌËLK-.Ñ
K-*ÎÌÏ³R0Ô3àår.JM,IMÑuª
)hø%&ç¤*8çä%– jòrñr PKÄs_/>   >   PK  |ltO            
   index.html³É(ÉÍ±ã²IÊO©´ãò,Q(Ï/ÊNMQä²Ñ‡ÙèCT  PKV¤‹µ#   )   PK
    åntO               WEB-INF/PK
    întO               WEB-INF/classes/PK
    õntO               WEB-INF/classes/ch12/PK  õntO            &   WEB-INF/classes/ch12/ShowSession.classV[WWþNH2! Q´±jÇT pïä¢HQi¹• Xmm'É‘ŒLfâÌ	‚ícŸû\ûxëZ®Õe>¸Ú>øÐÐÿÐ¿Ðåj»ÏLŒˆxÉZ9—}¾}ßûœùóß'OœÇ·q‚G';0‚ÑNÉùtúp&†³1œ“Ëó1\èÀ²rÈÅ£….ÆpIžw Ër˜Pð‰¤L&Hþ””õiÓ
fÌ2Ds¦mŠC[z`‰!<áT8C÷´ióÙF­ÄÝE£d%ZqæO0,¤§ïkÆºîqwÍâB¯
Q×¯ÑPü^ƒ{"ûN˜Wwlg¥Úøäz™×…Is
æ"ç*'}Ea”WgŒºoˆ‚Ï,((OÑi¸e~Å”æí)VûEîy$â„TÌ\hØÂ¬ñ%Ó3‰sÜ¶aø*zwg´õe^jZ˜eèh¸Ö¼!w%—ª{¤Å´¨ø‡U‡¦`QÅu‘²Å
WÅ2n¨ø‡)ž³FÌ‹,Vƒ«¸‰[í‚¯ËxÔ,_ªø
·U|oNç$±«r£RÈ	SX¼ ýÒšŽåô€–ÓDÉ©lT¸MÞæª#…&N›fðÊG(µGäÙ”­‰ªéiMóƒ³\Ã"%”UT@öÝÁ
ÅRÆF·{E/
×´WTTaý²ãO¸F}†‹ªSñº£¸Ãª
56œêrsƒ°åêÈ¨¾-)Gß^¯šôVe0ìó
3}jnõÍr›Š[lóäŒXvMJ'COmÓÒ'íF»F ®÷½ª›Êo…‹–ŠTzàÍåîc¨˜Tâ˜7\*ß€¾ ‘¶:;ð:‰4™öša™CP%©ã‚ŽJ
¹íßEÈ6Ê\é./¿ÅúÞ¯ºHÃ„cn‹Å:zv3”$¶“?/¢y°€a&ë•ºÜZ¤½+ÛL—}A-•|Á·3ÄÙ]5¼Çå“¯‘1žGÝ¤¦´©šD†ýé×‚½-Nï
v“/Ž{ oÚs–Y`Z^cäYÍXå²!–MQ¥•'ßšóïûÝRÚ¹Òª¤ëS;hÁþÎéÔ ¹:]	nA6ñx¥¢§AûÞqÜšVó»1ŸšŸ+.¦4£,Ã—O±TAÆxL£¾ÞšM›|J’Ršg>àùÑ“tƒ¸ÿfÚòi¯Âü€Tù”×(ÕL‘ÒÖ$6Ÿ*ÛÝ1Tÿrl1øwáuéCA'oŽûÇ_ÆêÞYåÍp)¸Bî9î†‚
z’¦gµQ§\OÙ6w',ÃódMý¸=/MÁuÍ°+÷ŽŒÙ·¦ïFÙ»Ào½=ÝM†e©²
4ï—wÚÖ¼ÖÞŒÃ1úF8ùk£÷œÞ"ÐîÍŒæÈà¯`hA¢hŒúÄ?‚†ý˜XÛhV3Cz	Ž $3JRùÌ!¤Îäs0³%„£³?2[hc˜Í$Â[ˆ„ðJxá¶³ážðC¨Ã[ˆ2l"“I(þùX$“ˆ«h2ò‰dô:‡“‘dtímJÄ·ÐÂÐTFèd$Ñù]RX'­»i½‰‹´ÚC+’¾—IAÄ›`xˆ>¹ÚÇðö)$SN’Úžžà  yÿû+!“2"}à“¤ß!ßïÛ8Hc

ùš$_¢—¾«úé£),0‰AÌa˜Þ÷ôbëô\Žb§ÐÀ|‡søž¾à~ÀüD_e?Ç#ðÆñ”æßq•¤d*Ïq@Aß%öÝ¬ÿ9zÐØ¥ ý†^‰w˜tJÛ‘¡¹‹â?Dÿá[`Y°ægŠA`,HâŠ	‘†kþøÙÿPK-
Öû`  X
  PK  õntO            )   WEB-INF/classes/ch12/ShowParameters.classU][E~'„lHÂwMµ-µ@Ãç–ªXI¥X
>$*j$c²d³w'ÿD×ÞPÃ…×>þ"/ªg6!á³mž'3{Î¼çwÎœ™ùûåÉŸ ¡Á `"ŒÉ(¦0­š™0f#¸#Š˜‹b£xïGq¨f^Ã‡ÊýHÃG, ÙOt«O4,jxÂJ™¶)Ó‰‰†à’S±Œi‹õZ%'Ümž³ÈÓYpž	É°•Èìó~hxÂ=°„4JRVj²
Ç–ø©&<™|-Ì«:¶'’jÖÈÓÃ¼¨J“–†¼’ós“h“»¼"¤p=†î¬äùò¯ú¢4|ªá©†e"È:57/–M%u KÑí°Y%„!¾U³¥Y;¦gRð¢m;’ûS2Œ]Ë[ƒÆ®È5'¢5×Úä’XUTÌP2«­‰taXÇ-Üdè’âP-ºbix¦c«:>Ãçë)åL§J‚Ò)iJK¤•Þ‘¶à”Ñp§Œ(çŽ(`.}Bfªf¥ud°ªaMÇ:6tlâ
[:²ØÖñ%vtìâ+†^µ<ÃâvÑÈJ×´‹:¾Æ7”©½ÌÅ‘¤†=ßâ;Šzâ8Ò“.¯®	Yr
^,„ïÃx®ãp9C¾4÷Ð8Ÿp†Û¯Þ{
ó§5cu£µõg¼›¤Dîº&±Ñ¦ûÞš4-ƒvž¡¿m¯€K‡@ãoVm=žKŽ-…-·ªäJ\ÎªÉ®¢hI¸‘˜È\¡*B«*Ó"ñcot,¨jˆ·•+A}§ì§k$ÞPYeU¦Îfý2ì>ç`›­<ŸƒŸæG	-qojÒ?è´õAÛ7Oñþò7rû"¯fè(*ÞñÄå±+á½í)]—Q	„¸—1ÕzÇ{×²ø
–Œ %=e™i6òx„QÒ+¼,h«ò\îš²D_žä¶$îù+¶ì"áÄe]byËñèÞª„M†Ñ6Æ´œ²hB³.ó<åîHC™–“qœr6K_µmá.YÜóIùå¬”&Gã´¬p»`	o´˜¼Nñå@U–WÀ¯ÏâYŠ%nYY*:ÆV³&_«­y^¯ÇÑK2@úu€©[ŽÚdÝ¢žQß9ùìwú`x‹Úï¤6Ž›øÐ{ÚA½695}Œ@! "èÛô$ÿ;>÷iè	†©/N÷wÔ`ºŽNºIgúCÇÐ¦ê3,ãÁ:ºêˆÕï¬#Êð+¨/á/t/„âÁx¨Žž Y±m&Šk ÷} 1ýöß?3ÇèWÒ¾´Iz,Ãô„Æð.-|œdÝÇ"&°A£Ïé
Îa?b·	Ù‡ÀKLi¸£aDÃÝ1fEA"PÄ÷0J}ùÆè?¾æeÉÏ#ª}))²Ãd?¦úPKÎXmÐ!    PK  õntO            &   WEB-INF/classes/ch12/HelloClient.class’ßnAÆ¿¡Àòg¥¤Xµµ¨E¨ÕI½2²!1D­	©
4mŒWL`Ì2‹»CCËM½ð|(ã™]¬¤&ê&{ÎÎo¾3çÛ™ùþãë7 Ïð(‡nf°‘Ç-Ü6áN›9lá®…mU†´#•Ô-†•zã„!Ùö‡‚aµ#•8œMú"8vû‘ÔÐ-4C·Þùàž¹sŠàÌšµžò
½tÅÇ™uóŸ²pê«P4M×ÜËù@Lµ$`áž…û„zþ,ˆWÒ4_;žç·=)”~bÖeØèÎ”–q"CI_(åk7ZaçJo÷r’ŸŠþÂ@“!?¼#Wk˜ª4›.6²È1dµ˜×ÏÂ;¨Ùxˆ:Ã;ÇÀ–3î°åh©=ÑŠìmÇþª¡ÃcIßž“|ÿªŠˆÃãÉ¨OËBÃÆ.jô¿ƒñþS¾ôÓ[ßÎ?~¹±%#àÒçoÞ.ÑÚÿC!ºí+MnŽÏ§ÊñMàž«F¼§©FÑafGBŸ’v•¡Rot~µ="Åb¢¹äf	3XS3òª°èêš'fN„bžF›”åÔî°OôÁ`SLGÐ¦x
*1Òç”“”×÷Š‰¬$°w$Ãáãbê3Ò¿k‹‘ê:µ+b%”Q¡lÖL`x‚¸±QÂ
Êª*Ó»þ,Då'PKË¦<û  k  PK   "otO           	                META-INF/þÊ  PK   "otOÄs_/>   >                =   META-INF/MANIFEST.MFPK   |ltOV¤‹µ#   )   
             ½   index.htmlPK
 
    åntO                           WEB-INF/PK
 
    întO                         >  WEB-INF/classes/PK
 
    õntO                         l  WEB-INF/classes/ch12/PK   õntO-
Öû`  X
  &             Ÿ  WEB-INF/classes/ch12/ShowSession.classPK   õntOÎXmÐ!    )             S  WEB-INF/classes/ch12/ShowParameters.classPK   õntOË¦<û  k  &             Ë  WEB-INF/classes/ch12/HelloClient.classPK    	 	 k      
  
As you can see not of much use`

**Comment by l0y** [comment]
Thanks for bringing this to my attention, Markus. As best I can tell, the war file remains in tact. My guess is that Notepad is not designed to support binary files. WAR files are "web archives" similar to JAR files (Java archives) which are really just ZIP compressed files at their core. They're meant for deployment in a servlet container. (See "Servlet Containers" starting on p422.) 

If you want to inspect the contents yourself, you'll need to unpack `ch12a.war` before trying to open any of its files in a text editor. I'm not a Windows guy, but any unzipping tool should work. With the JDK installed, you can also use the `jar` utility from a command window to work with WAR files, of course:

```
$ jar tvf ch12a.war 
     0 Wed Nov 20 13:57:04 EST 2019 META-INF/
    62 Wed Nov 20 13:57:04 EST 2019 META-INF/MANIFEST.MF
    41 Wed Nov 20 13:35:56 EST 2019 index.html
     0 Wed Nov 20 13:55:10 EST 2019 WEB-INF/
     0 Wed Nov 20 13:55:28 EST 2019 WEB-INF/classes/
     0 Wed Nov 20 13:55:42 EST 2019 WEB-INF/classes/ch12/
  2648 Wed Nov 20 13:55:42 EST 2019 WEB-INF/classes/ch12/ShowSession.class
  2056 Wed Nov 20 13:55:42 EST 2019 WEB-INF/classes/ch12/ShowParameters.class
   875 Wed Nov 20 13:55:42 EST 2019 WEB-INF/classes/ch12/HelloClient.class
```

(The `tvf` options just lists the table of contents for the WAR file; use the `xvf` options to extract.) Then you could read the text files like `MANIFEST.MF` in Notepad. Chapter 3 in _Learning Java_ has more information on tools like `jar` if you want to dig further.
